<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">{{ __('Item Variants') }}</h2>
            <a href="{{ route('inventory.variants.create') }}" class="inline-flex items-center rounded-md bg-gray-800 px-4 py-2 text-xs font-semibold uppercase tracking-widest text-white hover:bg-gray-700">{{ __('Create Variant') }}</a>
        </div>
    </x-slot>
    <div class="py-12"><div class="max-w-7xl mx-auto space-y-6 sm:px-6 lg:px-8">@if (session('status'))<div class="bg-white p-4 text-sm font-medium text-green-700 shadow-sm sm:rounded-lg">{{ session('status') }}</div>@endif<section class="bg-white shadow-sm sm:rounded-lg"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">{{ __('Variant') }}</th><th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">{{ __('SKU / Barcode') }}</th><th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">{{ __('Price') }}</th><th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">{{ __('Status') }}</th><th class="px-6 py-3 text-right text-xs font-medium uppercase tracking-wider text-gray-500">{{ __('Actions') }}</th></tr></thead><tbody class="divide-y divide-gray-200 bg-white">@forelse ($variants as $variant)<tr><td class="px-6 py-4"><div class="font-medium text-gray-900">{{ $variant->item?->brand?->name ? $variant->item->brand->name.' - ' : '' }}{{ $variant->item?->name }}</div><div class="text-sm text-gray-500">{{ $variant->variant_name }}</div></td><td class="px-6 py-4 text-sm text-gray-600">{{ $variant->sku ?? __('No SKU') }}<br>{{ $variant->barcode ?? __('No barcode') }}</td><td class="px-6 py-4 text-sm text-gray-600">{{ number_format((float) $variant->selling_price, 2) }}</td><td class="px-6 py-4 text-sm text-gray-600">{{ $statuses[$variant->status] ?? ucfirst($variant->status) }}</td><td class="px-6 py-4 text-right text-sm font-medium"><a href="{{ route('inventory.variants.show', $variant) }}" class="text-gray-700 hover:text-gray-950">{{ __('View') }}</a><a href="{{ route('inventory.variants.edit', $variant) }}" class="ms-3 text-gray-700 hover:text-gray-950">{{ __('Edit') }}</a></td></tr>@empty<tr><td colspan="5" class="px-6 py-8 text-center text-sm text-gray-500">{{ __('No variants found.') }}</td></tr>@endforelse</tbody></table></div><div class="border-t border-gray-200 px-6 py-4">{{ $variants->links() }}</div></section></div></div>
</x-app-layout>
