<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">{{ $expense->description }}</h2>
            <a href="{{ route('expenses.edit', $expense) }}" class="inline-flex items-center rounded-md bg-gray-800 px-4 py-2 text-xs font-semibold uppercase tracking-widest text-white hover:bg-gray-700">{{ __('Edit') }}</a>
        </div>
    </x-slot>
    <div class="py-12"><div class="max-w-4xl mx-auto space-y-6 sm:px-6 lg:px-8">@if (session('status'))<div class="bg-white p-4 text-sm font-medium text-green-700 shadow-sm sm:rounded-lg">{{ session('status') }}</div>@endif<section class="bg-white p-6 shadow-sm sm:rounded-lg"><dl class="grid gap-6 md:grid-cols-3"><div><dt class="text-sm text-gray-500">{{ __('Date') }}</dt><dd class="font-medium text-gray-900">{{ $expense->expense_date?->format('M d, Y') }}</dd></div><div><dt class="text-sm text-gray-500">{{ __('Amount') }}</dt><dd class="font-medium text-gray-900">{{ number_format((float) $expense->amount, 2) }}</dd></div><div><dt class="text-sm text-gray-500">{{ __('Status') }}</dt><dd class="font-medium text-gray-900">{{ $statuses[$expense->status] ?? ucfirst($expense->status) }}</dd></div><div><dt class="text-sm text-gray-500">{{ __('Branch') }}</dt><dd class="font-medium text-gray-900">{{ $expense->branch?->name ?? __('Company-wide') }}</dd></div><div><dt class="text-sm text-gray-500">{{ __('Category') }}</dt><dd class="font-medium text-gray-900">{{ $expense->category?->name ?? __('Uncategorized') }}</dd></div><div><dt class="text-sm text-gray-500">{{ __('Reference') }}</dt><dd class="font-medium text-gray-900">{{ $expense->reference_number ?? __('Not set') }}</dd></div><div><dt class="text-sm text-gray-500">{{ __('Created by') }}</dt><dd class="font-medium text-gray-900">{{ $expense->creator?->name ?? __('Not set') }}</dd></div><div class="md:col-span-2"><dt class="text-sm text-gray-500">{{ __('Attachment') }}</dt><dd class="font-medium text-gray-900">@if ($expense->attachment_path)<a href="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($expense->attachment_path) }}" class="text-gray-700 underline hover:text-gray-950" target="_blank">{{ __('View attachment') }}</a>@else{{ __('Not set') }}@endif</dd></div></dl></section><section class="bg-white p-6 shadow-sm sm:rounded-lg"><form method="POST" action="{{ route('expenses.destroy', $expense) }}" onsubmit="return confirm('{{ __('Delete this expense?') }}')">@csrf @method('DELETE')<x-danger-button>{{ __('Delete Expense') }}</x-danger-button></form></section></div></div>
</x-app-layout>
